#!/usr/bin/perl

use strict;
use warnings;
use Digest::MD5 'md5_hex';

my $tmpdir = '/tmp';

local $/;
my $input = <>;

my $src = <<EOF;
\\documentclass{article}
\\usepackage{amsmath}
\\usepackage{pb-diagram}
\\pagestyle{empty}
\\begin{document}
\\[ $input \\]
\\end{document}
EOF

my $md5 = md5_hex($src);
my $filename = "$tmpdir/$md5";
open(my $fh, '>', "$filename.tex");
print $fh $src;
close $fh;

`pdflatex -output-directory $tmpdir $filename.tex`;
`convert -density 120 -trim $filename.pdf $filename.png`;
`mv -f $filename.png .`;

print "$md5.png";

